bnb-chain/op-geth

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
Add issue and pull request templates.
To enhance the context for pull requests and issues.
NA
NA
> chore: add issue and pull request templates

- CHANGELOG.md
- params/config.go
Add changelog doc and testnet Fermat height.
NA
NA
NA
> chore: add changelog doc and testnet Fermat height

- CHANGELOG.md
- params/config.go
Add opBNB mainnet Fermat fork height.
NA
NA
NA
> feat: add opbnb mainnet Fermat fork height

- CHANGELOG.md
> chore: add changelog doc

- CHANGELOG.md
Update v0.2.2 changelog.
NA
NA
* NA
> doc: update v0.2.2 changelog

- CHANGELOG.md
Update v0.3.1 changelog.
NA
NA
NA
> doc: update v0.3.1 changelog

- params/config.go
update opBNB qanet config
* ...
> feature(op-geth): update opBNB qanet config

- params/config.go
add opBNB qanet hard fork config
* ...
> feature(op-geth): add opBNB qanet hard fork config

- core/vm/contracts_test.go
Add example for testing bls verify precompile contract
Add testcase
NA
* NA
> add bls example

- core/block_validator.go
- core/blockchain.go
- core/state/statedb.go
> fix: update by comment tips

- core/txpool/legacypool/legacypool.go
add some metrics for txpool, mainly about the latency of txpool runReorg procedure.
> add some metrics for txpool

- core/txpool/legacypool/cache_for_miner.go
- core/txpool/legacypool/legacypool.go
need to re-apply filter in txpool Pending() method after merging code from upstream v1.101315.2
> fix: txpool legacy pool Pending() applies filter

- core/txpool/bundlepool/bundlepool.go
- core/txpool/bundlepool/bundlepool_test.go
Fix bundle pool issue.
Every time when dropped a bundle, should compare the price again. Otherwise, a huge bundle whose price is only higher the the minimal price bundle will result in other bundles dropped.
N/A
* change bundle pool drop logic.
> fix addBundle issue

- CHANGELOG.md
Add CHANGLOGS to v0.4.3.
NA
NA
NA
> doc: add changelogs to v0.4.3

- CHANGELOG.md
- core/txpool/bundlepool/bundlepool.go
- core/txpool/bundlepool/bundlepool_test.go
- ethclient/ethclient.go
- trie/triedb/pathdb/disklayer.go
prepare for v0.4.6 release
NA
NA
NA
> prepare for v0.4.6 release

- core/state/parallel_statedb.go
- core/state/statedb.go
> PEVM-opt: Parallel KV check and add stateObject no update cache

- core/parallel_state_processor.go
pevm: add a side slot to trigger next tx advance;
* pevm: add a side slot to trigger next tx advance;
* ...
> pevm: add a side slot to trigger next tx advance;

- CHANGELOG.md
Add v0.5.0 change log
Add v0.5.0 change log
N/A
* Add v0.5.0 change log
> feature(op-geth): add v0.5.0 change log

- CHANGELOG.md
Update v0.5.0 changelog.
NA
NA
NA
> doc: update v0.5.0 changelog

- miner/worker.go
bugfix: estimate the correct gas for TxDAG transaction
> fix: estimate the correct gas for TxDAG transaction

- miner/worker.go
> fix: correctly estimate the max gaslimit for TxDAG data

- cmd/utils/flags.go
- core/blockchain.go
- core/parallel_state_processor.go
- core/state/parallel_statedb.go
- core/state/statedb.go
- core/state/statedb_test.go
> PEVM-fix: refine dispatcher and fix memory issues.

- core/parallel_state_processor.go
> PEVM-opt: parallel Txs Prepare

- core/parallel_state_processor.go
- core/state/parallel_statedb.go
- core/state/state_object.go
- core/state/statedb.go
> PEVM-opt: Remove deepcopy and useless fixup at merge phase

- core/state/statedb.go
- core/types/dag.go
- core/types/dag_test.go
- core/types/mvstates.go
- core/types/mvstates_test.go
- miner/worker.go
> txdag: clean codes;

- params/bootnodes.go
add bootnode in us region(testnet)
> chore: add bootnode in us region(testnet)

- cmd/utils/flags.go
- core/parallel_state_scheduler.go
- core/pevm_processor.go
use ParallelTxNum config and uber automaxprocs
> fix: use ParallelTxNum config and uber automaxprocs

- Release Note - TxDAG based parallel transaction execution (PEVM).md
Add release note for TxDAG-PEVM alpha release.
NA
NA
NA
> doc: add release note for TxDAG-PEVM alpha release

- CHANGELOG.md
Add changelogs to v0.5.3
NA
NA
NA
> doc: add changelogs to v0.5.3

- core/blockchain_test.go
> fix: Add test for PEVM fall back

- CHANGELOG.md
Add changelogs to v0.5.4
NA
NA
NA
> doc: add changelogs to v0.5.4

- CHANGELOG.md
Add changelog to v0.5.5
NA
NA
NA
> doc: add changelogs to v0.5.5

- core/txpool/legacypool/async_priced_list.go
The async priced list might block the graceful shutdown when the chain is stopped. This PR makes every method of AsyncPricedList impossible to blocked when the `quit` channel is closed;
It also merge the events of `SetBaseFee` and `reheap`.
> gracefully shutdown when the async priced list is closed

- core/blockchain.go
> chore: fix cherry-pick conflict

- CHANGELOG.md
- beacon/engine/types.go
- consensus/beacon/consensus.go
- consensus/ethash/consensus.go
- core/blockchain.go
- core/blockchain_insert.go
- core/chain_makers.go
- core/headerchain.go
- core/txpool/blobpool/blobpool.go
- core/txpool/legacypool/cache_for_miner.go
- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
- core/txpool/legacypool/nonecache_for_miner.go
- core/types/block.go
- core/vm/evm.go
- eth/catalyst/api.go
- eth/catalyst/api_test.go
- eth/catalyst/simulated_beacon.go
- eth/gasprice/feehistory.go
- graphql/graphql.go
- internal/ethapi/api.go
- internal/ethapi/api_test.go
- miner/miner.go
- miner/payload_building.go
- miner/worker.go
Merge for releasing v0.5.7
No.
No.
No.
> feat: merge for releasing v0.5.7
