- .github/workflows/docker-release.yml
add the ci code used to package and release docker images
Execution effect:
Note:
Need to open the write permission of github_token, path: settings->Actions->General->Workflow permissions
> ci: add docker release workflow to build and release docker image

- cmd/evm/internal/t8ntool/execution.go
- consensus/misc/precontract.go
- core/chain_makers.go
- core/state_processor.go
- miner/worker.go
- params/config.go
This feature is add preDeployedContract hardfork to change preDeployed contract `WBNB` `name` and `symbol`, and remove preDeployed contract GovernanceToken.
The preDeployed contract `WBNB` address is `0x4200000000000000000000000000000000000006` , `name` and `symbol` is not correct, so it should be changed to `Wrapped BNB` and `WBNB`. And `OP-BNB` doesn't need GovernanceToken,
so the preDeployed contract `4200000000000000000000000000000000000042` should be removed.
Set preDeployed contract `WBNB` `name` to `Wrapped BNB`.
Set preDeployed contract `WBNB` `symbol` to `WBNB`.
Remove preDeployed contract `4200000000000000000000000000000000000042`
> feat: add preDeployedContract hardfork

- .github/workflows/docker-release.yml
Refactor Docker release workflow and image metadata.
Previously, the Docker release workflow built and published the Docker image only when a `v*` tag was pushed. However, we now have additional scenarios where we need the Docker image, such as deploying and testing a specific feature before its release. Therefore, we have added more conditions that will trigger the building of Docker images.
Events and the associated docker tags
Event | Ref | Docker Tags
-- | -- | --
push | refs/heads/main | main
push | refs/heads/develop | develop
push tag | refs/tags/v1.2.3 | v1.2.3, 1.2.3
push tag | refs/tags/v2.0.8-beta.67 | v2.0.8-beta.67, 2.0.8-beta.67
workflow_dispatch | refs/heads/main | main
A tag associated with the given git commit hash like `sha-ad132f5` will also be added.
* …
> ci: refactor docker release workflow and image metadata

- eth/handler.go
- eth/protocols/snap/handler.go
**Description**
This feature is related to [PR #105](https://github.com/ethereum-optimism/op-geth/pull/105). 
**Rationale**
It's a small fix for Geth’s snap sync for op chains.
**Example**
NA
**Changes**
1.  adds a fallback logic for the legacy keys to serve bytecodes for snap sync
> feat: support snap sync for OP chains

- cmd/geth/snapshot.go
- core/state/pruner/pruner.go
**Description**
NewPruner() creates a new snapshot, but it doesn't pass a SnapshotOption function, so the snapshot will always have a limit of 128 layers here.
**Rationale**
Add SnapshotOption config when creates a new snapshot
**Changes**
Pass SnapshotOption in NewPruner() when creating new snapshot
> fix: pass a SnapshotOption func when init a new pruner

- .github/workflows/review-assign.yml
Implemented a feature to automatically assign two reviewers to a PR using a bot.
This automation streamlines the review process, ensuring that each PR is reviewed by at least two team members, thereby maintaining code quality and consistency.
Upon PR submission, the bot automatically assigns two reviewers from the team.
* Created a script for the bot to randomly select and assign two reviewers to a PR.
* Integrated the bot script with the existing CI/CD pipeline.
> chore(ci): randomly assign 2 reviewers with bot

- .github/workflows/docker-release.yml
- Dockerfile
Fix `Caught SIGILL in blst_cgo_init` error in docker image.
Prevent unknown architecture and OS in result.
references
- https://github.com/docker/build-push-action/issues/820
- https://github.com/bnb-chain/bsc/issues/1521
- https://github.com/bnb-chain/bsc/blob/master/Dockerfile
NA
NA
> ci: fix blst error and unknown architecture

- cmd/utils/flags.go
- params/bootnodes.go
Add `opBNB` testnet and mainnet bootnodes in code.
Add `opBNB` testnet and mainnet bootnodes in code can facilitate the startup of new nodes.
The startup node will use the `opBNB` mainnet's bootnodes by default. If the `--networkid` is configured and it is testnet, the testnet bootnodes will be used. If `--bootnodes` is configured, the configured bootnodes will be used. The configured `--bootnodes` have the highest priority.
Add `opBNB` testnet and mainnet bootnodes in code.
> feature: add opBNB bootnodes

- core/state/pruner/pruner.go
This message is not updated to reflect the optimization of TriesInMemory diff layers. Currently, the number is variable and not fixed at 128.
fix wrong event log value
none
- fix wrong log value
> fix: wrong event log value[BNB-8]

- core/types/transaction.go
- eth/fetcher/tx_fetcher.go
- eth/fetcher/tx_fetcher_test.go
This is a bug fix: In some special situations, some transactions with enough gas price might stuck forever in pool.
The detail had been reported to official repo in go-ethereum, here is it https://github.com/ethereum/go-ethereum/issues/28018.
And the fix solution had been adopted by official team, here are the fixes:
(1) https://github.com/ethereum/go-ethereum/commit/2b7bc2c36b0d0efc83e62ba8e13723b943c4fa6e
(2) https://github.com/ethereum/go-ethereum/commit/667966c5c10e7bf1e38a0439c62b11d5b26a132a
> fix: clear underpriced buffer

- core/blockchain.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
Currently, all of our nodes can only be set to archive mode for gcMode. As the amount of data gradually increases, each of our nodes needs to be able to configure to full mode. This mode will delete Trie data that is lower than the latest block height minus TriesInMemory blocks, instead of committing and storing it in the database. This way, our nodes will occupy less disk space and have better performance. However, our official bridge and proposer components both need to use Trie data from about 1 hour ago. After enabling full mode, both the official bridge and proposer components will not function properly.
We need to enable full mode, and at the same time, we need to solve the problem of the official bridge and proposer using Trie data.
It should be noted that the full mode does not …
> feat: add TrieCommitInterval configuration, commit trie every TrieCommitInterval blocks.

- core/blockchain.go
remove commitLock in BlockChain struct
In the `blockchain.go:writeBlockWithState()` function, the first function of the `postCommitFuncs` uses the `bc.commitLock` . However, this lock appears unnecessary, as it is only used for this function and the function concludes after `state.Commit()` . We have not identified any specific data that require this lock.
none
* remove commitLock in BlockChain struct
> fix: remove redundant lock[BNB-20]

- eth/bloombits.go
- p2p/dial.go
Use `go` to run long-running tasks instead of gopool
The gopool limits the go-routines to run at a time, keeping the total go-routine memory in a manageable state.
However, for a long-running task, it will occupy a worker from the pool and never return, causing the effective pool size to decrease. 
none
* Use `go` to run long-running tasks instead of gopool
> fix: refraining from using gopool for long-running tasks[BNB-19]

- core/blockchain.go
bubbling up the error when DeriveField() fails.
In `blockchain.go:insertChain()`, the `types.Receipts(receipts).DeriveField()` call can potentially return an error. In the case that the `DeiveField()` fails, the receipts will not have the expected data attached to it. However, the code caches the block data ( `CacheBlock()` ) and the receipt data ( `CacheReceipts()` ) no matter whether the `DeriveField()` errors out or not in the `insertChain()` function. Incomplete or invalid data can be cached and risk causing unexpected scenario.
none
* bubbling up the error when DeriveField() fails.
* bc.reportBlock and close(interruptCh) is the aftermath work that must be included
> fix: bubbling up the error when DeriveField() fails[BNB-13]

- core/txpool/txpool.go
add metric for staled transaction in txpool. It works only if the reannouncement function is enabled. The new metric is:
`txpool/staled/count`
> chore: add reannounce metric for txpool

- cmd/geth/dbcmd.go
- trie/inspect_trie.go
- trie/trie.go
Cherry-pick inspect mpt tool from bsc.
https://github.com/bnb-chain/bsc/pull/2082
https://github.com/bnb-chain/bsc/pull/2142
N/A.
N/A.
* CMD: add inspect mpt tool.
> feat: sync inspect mpt tool from bsc

- cmd/utils/flags.go
- core/blockchain.go
- core/blockchain_insert.go
- core/blockchain_snapshot_test.go
- core/blockchain_test.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- eth/state_accessor.go
- eth/tracers/api.go
- trie/database.go
- trie/triedb/hashdb/database.go
- trie/triedb/pathdb/asyncnodebuffer.go
- trie/triedb/pathdb/database.go
- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/errors.go
- trie/triedb/pathdb/journal.go
- trie/triedb/pathdb/layertree.go
- trie/triedb/pathdb/nodebuffer.go
Add async buffer to improve performance in the tire commit phase of the path-base scheme.
N/A.
N/A.
* path/database.
> feat: add async buffer

- CHANGELOG.md
add v0.3.0 changlog
prepare for next release
n/a
add v0.3.0 changlog
> chore: add v0.3.0 changlog

- cmd/geth/dbcmd.go
- core/rawdb/database.go
- trie/hbss2pbss.go
- trie/node.go
Add hbss to pbss convert tool for generate opBNB snapshot more quickly.
If starts from the genesis block to make the opBNB snapshot, it will takes some time.
If using the convert tools and convert hbss trie node to pbss trie node, it will takes about 2 days.
```shell
./geth db hbss-to-pbss --datadir ./node 1000 
./geth db prune-hash-trie  --datadir ./node
./geth db compact --datadir ./node
```
NOTICE: it will take a long time to iterate the entrie databse.
* Add hash2path/prune-hash-trie tools for convert and prune the hbss trie node.
* Add trieGet/trieDelete for pbss to debug and handle exceptions.
> cmd/geth: add hbss to pbss convert tool

- crypto/crypto.go
This is part of the optimizations from BSC, microbench show the change could introduce  ~20% speed up of simple erc20 transfer scenario.
The original PR of BSC: https://github.com/bnb-chain/bsc/pull/257
> feat: introduce hash cache to improve performance

- trie/triedb/pathdb/nodebufferlist.go
Fix base buffer concurrent read/write race.
Fix the map in the base from being accessed and modified concurrently.
N/A.
* pathdb bufferlist.
> fix: fix base buffer concurrent read/write race

- core/state_processor.go
- miner/worker.go
revert disable create2deployer in canyon fork
create2deployer is a precontract now in upstream, we better consist with it
n/a
revert disable create2deployer in canyon fork
> canyon fork: revert disable create2deployer in canyon fork

- core/vm/contracts.go
add precompiled contracts for light client validation
The precompiled contracts for light client validation should not be removed here.
NA
* NA
> add precompiled contracts for light client

- cmd/utils/flags.go
Add `opBNB` testnet and mainnet V5 bootnodes in code.
Add `opBNB` testnet and mainnet V5 bootnodes in code can facilitate the startup of new nodes.
The startup node will use the `opBNB` mainnet's V5 bootnodes by default. If the `--opBNBTestnet`  is configured the testnet V5 bootnodes will be used. If the `--networkid` is configured and it is testnet, the testnet V5 bootnodes will be used. If `--bootnodes` is configured, the configured bootnodes will be used. The configured `--bootnodes` have the highest priority. The `--networkid` have the lowest priority.
* Add `opBNB` testnet and mainnet V5 bootnodes in code can facilitate the startup of new nodes.
> feature: add opBNB V5 bootnodes

- core/blockchain.go
In https://github.com/bnb-chain/op-geth/pull/45, I added a TrieCommitInterval parameter for periodically committing trie data for specific block heights when gcMode=full. However, I missed an extreme case during restart where the block height that needs to be committed is within a range of 128 block heights, causing the data to be lost from memory and not recovered upon restarting. We need to fix this problem.
In the Stop function, the data of the latest block height minus 0, the latest block height minus 1, and the latest block height minus 127 will be automatically committed.
If TrieCommitInterval is not equal to 0, then I will calculate an additional offset, so that the code can automatically commit the data of the block height specified by TrieCommitInterval.
none
* …
> fix: the TrieCommitInterval not taking effect on restart

- params/config.go
This is a configuration modification, expected to launch Shanghai and Canyon forks on May-15-2024 at 06:10 AM +UTC on the Testnet network, and launch Cancun and Ecotone forks on May-15-2024 at 06:30 AM +UTC.
N/A
N/A
* configuration modification
> config: Testnet 4844 fork time

- cmd/geth/dbcmd.go
- trie/inspect_trie.go
Add inspect trie tool to analysis the trie tree more convenient.
- https://github.com/bnb-chain/bsc/pull/2082
- https://github.com/bnb-chain/bsc/pull/2142
N/A
```
./geth db inspect-trie --datadir server/data-seed/ latest 4000
```
* N/A
> cmd/dbcmd: add inspect trie tool

- core/vm/evm.go
- core/vm/interpreter.go
When we merged version 1.7.2 of the upstream code for opbnb into our repository, this PR was missing from the content of the op-geth version it depends on. This PR was submitted in v1.101308.3, but our op-geth repository only merged the code from upstream v1.101308.2.
This PR has no impact on the block production logic, only affects the CI of the opbnb repository and the code in op-program, so there is no need for urgent repair. This is a change made to fix the CI of the opbnb repository.
This PR is cherry-picked from upstream code in order to fix the CI of the opbnb repository.
none
* cherry-picked upstream code
* ...
> fix: cherry-picked from upstream code

- miner/payload_building.go
During the merge process at https://github.com/bnb-chain/op-geth/pull/87, we missed a segment of code that enables caching, causing a performance decrease in geth, but it won't affect the core logic. We need to fix that code.
N/A
none
* Fix the missing cache enable code
> fix: add miss cache code after 4844 merge

- trie/triedb/pathdb/nodebufferlist.go
Adjust the flush condition to avoid the small probability of not flushing.
The diff to base condition:
https://github.com/bnb-chain/op-geth/blob/ee3412801cdd4834ac0fc03d481c96a05eddd5c8/trie/triedb/pathdb/nodebufferlist.go#L465-L469
and the background base flush condition:
https://github.com/bnb-chain/op-geth/blob/ee3412801cdd4834ac0fc03d481c96a05eddd5c8/trie/triedb/pathdb/nodebufferlist.go#L593-L595
should be consistent.
N/A.
* bufferlist.
> fix: adjust flush condition to avoid not flush

- params/config.go
Modify the configuration to add the activation time of the Shanghai/Canyon, Delta, Cancun/Ecotone and Haber forks on the Mainnet.
Activation time is as follows:
Shanghai/Canyon Time: 2024-06-20 08:00:00 AM UTC
Delta Time: 2024-06-20 08:10:00 AM UTC
Cancun/Ecotone Time: 2024-06-20 08:20:00 AM UTC
Haber Time: 2024-06-20 08:30:00 AM UTC
We will activate these hard forks on the mainnet.
none
* Change the mainnet's default configuration to increase the hard fork activation time.
> config: Mainnet Shanghai/Canyon/Cancun/Ecotone/Haber fork time

- cmd/geth/chaincmd.go
- cmd/geth/dbcmd.go
- cmd/geth/main.go
- cmd/geth/snapshot.go
- cmd/utils/flags.go
- core/blockchain.go
- eth/backend.go
- eth/ethconfig/config.go
- eth/ethconfig/gen_config.go
- node/node.go
- trie/triedb/pathdb/database.go
- trie/triedb/pathdb/difflayer_test.go
- trie/triedb/pathdb/journal.go
- trie/triedb/pathdb/nodebufferlist.go
This PR provides another way to persist TrieJournal by write it into a log file instead of a kv database.
Use `--journalFile` flag to enable/disable the journal file feature.
Persisting TrieJournal to KV database will cause problems below
- Additional WAL and compaction overhead in pebble/leveldb
- Big kv (>= 2GB) not supported by pebbledb. ([Size out of bounds when write kv >= 2GB](https://github.com/cockroachdb/pebble/issues/3333))
**Data Format**
Journal Version
Disk Root
Disk Layer
- Root
- State ID
- Buffer Nodes
- `Layer Checksum`
Diff Layer
- Root
- Block
- Trie Nodes
- Journal Accounts
- `Layer Checksum`
Journal Path: geth/chaindata/ancient/state.journal
Checksum: SHA256
Scenario: Using TestJournal, each layer has 4K and 8K account operations.
|            | WriteJournal | …
> core/trie: persist TrieJournal to journal file instead of kv database

- eth/backend.go
- internal/build/util.go
- trie/triedb/pathdb/database.go
- trie/triedb/pathdb/difflayer.go
- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/layertree.go
- trie/triedb/pathdb/metrics.go
Cherry-pick from bsc, https://github.com/bnb-chain/bsc/pull/2508.
Refer to cherry-pick PR.
N/A.
* Pbss difflayer: add hash cache.
* Pbss disklayer: adjust clean cache size.
> perf: speedup pbss trienode read

- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/metrics.go
- trie/triedb/pathdb/nodebufferlist.go
When using nodebufferlist in pathdb, geth should maintain three node cache in memory for withdrawal proof. This pr fixes a case that when the length of history is greater than `StateHistory` but not beyond maxBufferSize, nodebufferlist still should keep three node cache.
Start a load test that uses 1000 accounts and 1TPS for about 50 hours to verify this pr, metrics are shown below:
N/A
N/A
* N/A
> pathdb: handle persistent id when using nodebufferlist

- beacon/engine/errors.go
- core/blockchain.go
- eth/catalyst/api.go
This PR is part of the geth code for automatically recovering PBSS after an abnormal shutdown. It adds an inconsistent state to mark situations where the state and block data are inconsistent, along with subsequent data deletion handling.
this feature is for automatically recovering PBSS after an abnormal shutdown
N/A
* _inconsistent_ state added
* delete data func added
> feat: support auto recover when pbss meet unclean shutdown

- trie/triedb/pathdb/disklayer.go
- trie/triedb/pathdb/history.go
- trie/triedb/pathdb/history_test.go
ignore truncation target range as unclean shutdown happens
bufferlist meet an update failure when unclean shutdown happens and lead to a panic, ignore the range judgement in this scenario
N/A
> fix: ignore truncation target range as unclean shutdown happens

- params/config.go
Modify the configuration to add the activation time of the `Wright` hard fork on the Mainnet.
Activation time is  2024-08-27 06:00:00 AM UTC.
We will activate the hard fork on the mainnet.
None
* Change the mainnet's default configuration to increase the hard fork activation time.
> feature(op-geth): add mainnet wright hard fork time

- params/config.go
Update qanet config.
Update qanet config for test.
N/A.
*Update qanet chain config.
> feature(op-geth): update qanet config

- ethclient/ethclient.go
add DialOptions function for Dial 
eoa-paymaster need to get opbnb block data continualy，so a long link needs to be created
eoa-paymaster is a service for gasless project
> perf: add DialOptions function for Dial

- core/txpool/bundlepool/bundlepool.go
- core/txpool/bundlepool/bundlepool_test.go
Fix bundle pool issue.
Every time when dropped a bundle, should compare the price again. Otherwise, a huge bundle whose price is only higher the the minimal price bundle will result in other bundles dropped.
N/A
* change bundle pool drop logic.
> fix bundle pool issue

- trie/triedb/pathdb/disklayer.go
This PR aims to fix a potential memory leak issue in nodebuffer.
In #121 we introduced a potential memory leak risk. When the block height difference between stateid and truncate tail in the differlayer exceeds the limit size (90,000), we attempt to trigger a truncate. However, to prevent repeated deletions, we added a condition. If the condition is not met, we do not perform the truncate and return directly, waiting until the next trigger. Before returning, we forgot to clear the difflayer cache, which causes the difflayer to be unrecoverable, resulting in a memory leak. The diagram shows the monitoring of this part of the memory (pathdb_difflayer_hashcache_size).
The metric shows the memory usage of difflayer before and after enabling this fix.
N/A
> Fix: clear difflayer cache when truncate not triggered

- core/state/parallel_statedb.go
The stage2 conflict check is concurrently check the Tx and stateDB, there is possibility that stateDB is updated to latest version which is newer than the tx. in this way, skip the check.
There can be incorrect conflict check result.
> PEVM-fix: avoid checkout old tx in stage2 conflict check

- cmd/geth/main.go
- cmd/utils/flags.go
- core/blockchain.go
- core/state/journal.go
- core/state/state_object.go
- core/state/statedb.go
- core/state/statedb_fuzz_test.go
- core/state_processor.go
- core/state_transition.go
- core/types/dag.go
- core/types/dag_test.go
- core/types/mvstates.go
- core/types/mvstates_test.go
- core/vm/interface.go
- eth/backend.go
- eth/ethconfig/config.go
- miner/miner.go
- miner/worker.go
The implementation of [BEP-396: Accelerate Block Execution by TxDAG](https://forum.bnbchain.org/t/bep-396-accelerate-block-execution-by-txdag/2869).
* txdag: the initial the TxDAG commit;
* ...
> feat: support TxDAG generation for op-geth;

- core/blockchain.go
- core/parallel_state_processor.go
- core/vm/interpreter.go
pevm: fix some bad check & support to fallback to serial processor;
* pevm: fix some bad check & support to fallback to serial processor;
* ...
> pevm: fix some bad check & support to fallback to serial processor;

- eth/catalyst/api.go
- eth/catalyst/api_test.go
- eth/downloader/skeleton.go
When op-geth exits due to certain exceptional circumstances and the truncate operation results in the deletion of head data, the block-by-block insertion requests from op-node will trigger an EL sync in geth. This PR addresses this situation.
related op-node pr: [https://github.com/bnb-chain/opbnb/pull/222](url)
Instead of ignoring the unexpected EL sync triggers, specific errors are returned. op-node will handle them based on the state.
N/A
> (op-geth) Add extra error info when meet an unexpected el sync

- params/config.go
Modify the configuration to add the activation time of the `Fjord` hard fork on the Testnet.
Activation time is 2024-09-10 06:00:00 AM UTC.
Modify the configuration to add the activation time of the `Fjord` hard fork on the Mainnet.
Activation time is 2024-09-24 06:00:00 AM UTC.
We will activate the hard fork on the testnet and mainnet.
None
* Change the testnet and mainnet's default configuration to increase the hard fork activation time.
> feature(op-geth): add Fjord hard fork time

- core/state/state_object.go
- core/state/statedb.go
- core/types/mvstates.go
- core/types/mvstates_test.go
mvstates: abandon RWKey, using origin key to record rwset
mvstates: support txdepMap to produce txdag;
mvststes: using struct in rwset;
* ...
> txdag: opt generation performance;

- core/rawdb/chain_iterator.go
- core/rawdb/chain_iterator_test.go
- core/txindexer.go
- core/txindexer_test.go
This PR fix `engine_forkchoiceUpdated` api performance issue, which is introduced from upstream geth code.
1. `engine_forkchoiceUpdated` api blocks on [chainHeadFeed.Send](https://github.com/bnoieh/op-geth/blob/732b95e70d919dfa7ee26010fdb5561e09ee168b/core/blockchain.go#L2460), which waits for all the feed subscribers to receive.
2. [txIndexer](https://github.com/bnoieh/op-geth/blob/0085f637eb420dbc593b4d1bd06c66e77241a6f5/core/txindexer.go#L137) is one of subscribers, it may take about 800ms to receive, and the bad apple is `rawdb.ReadTxIndexTail`. You could [find more details here](https://github.com/ethereum/go-ethereum/issues/28907)
3. opBNB block time is 1s, and can not afford this high latency of engine api
n/a
1. cache `lastTail` in `txindexer.go` to avoid read from db
> feat: cache lastTail in txindexer to avoid read from db

- core/blockchain.go
- core/state/parallel_statedb.go
- core/state/statedb.go
> pevm-opt: lock free localstateObjects

- .github/workflows/docker-release.yaml
We need to support arm64 architecture Docker images
Just add the parameters `platforms: linux/amd64,linux/arm64`.
none
* docker-release.yml
> fix(ci): support building arm64 architecture

- core/types/mvstates.go
txdag: support find all prev tx from rw list;
* ...
> txdag: support find all prev tx from rw list;

- core/types/mvstates.go
We need to ensure that write transactions on the data occur after read transactions. Therefore, if there is a read transaction before a write transaction, the read transaction will be added to the dependency list.
> txdag: Add the dependency of read-before-write to the DAG

- core/types/mvstates.go
txdag: add suicide checking logic;
* ...
> txdag: add suicide checking logic;

- core/types/mvstates.go
When a read operation is accompanied by a write operation, there is no need to include it in the readSet because it will be filtered out later. We only need to record pure read operations.
> txdag: optimize the size of readSet

- core/types/dag.go
> PEVM-fix: check in ValidatePlainTxDAG

- CHANGELOG.md
This release includes various optimizations and improvements to transaction processing, CI support, and network infrastructure.
This is a minor release for opBNB Mainnet and Testnet.
Upgrading is optional.
* fix(ci): support building arm64 architecture (#165)
* optimization: enqueue transactions in parallel from p2p (#173)
* optimization: enlarge p2p buffer size and add some metrics for performance monitor (#171)
* optimization: txpool pricedlist only reheap when pool is full (#175)
* optimization: txpool pending cache improvement (#177)
* chore: add bootnode in us region(testnet) (#194)
ghcr.io/bnb-chain/op-geth:v0.5.1
**Full Changelog**: https://github.com/bnb-chain/op-geth/compare/v0.5.0...v0.5.1
> doc: add changelogs to v0.5.1

- core/pevm_processor.go
- core/state/pevm_statedb.go
- core/state/pevm_statedb_test.go
bugfix: 'invalid gas used'
1. add testcases for selfdestruct and create, which focus on balance
2. add unit test for the false cache, which lead to 'invalid gas used'
3. fix the false state of cache in uncommittedDB
4. add a unit test case for GetCode()
> Fix/pevm v0.5.0 invalid gas used

- cmd/geth/main.go
- cmd/utils/flags.go
- core/blockchain.go
- core/parallel_state_scheduler.go
- core/pevm_processor_test.go
- core/state_processor.go
- core/vm/interpreter.go
- eth/backend.go
- eth/ethconfig/config.go
- tests/block_test_util.go
do some args optimizations:
1. '--parallel2' is remove.
2. '--parallel'  will be used instead of '--parallel2'.
3. '--parallel-legacy' is added for the old version of pevm.
4. add log info when enabling parallel evm.
> rename pevm option

- core/blockchain.go
- core/pevm_processor.go
- core/state/pevm_statedb.go
- core/state_processor.go
If TxDAG is nil, then use the serial processor to handle it.
The current version of TxDAG reads from a file, so it may not be able to read after a certain block height, and a serial processor should be used to execute it.
> pevm: If TxDAG is nil, then use the serial processor to handle it.

- core/parallel_state_scheduler.go
- core/parallel_state_scheduler_test.go
- core/state/pevm_journal.go
- core/state/pevm_statedb.go
- core/state/pevm_statedb_test.go
The case of `go test -run TestExecutionSpecBlocktests` failed when run in `tests` dir. It said: `invalid gas used` and `invalid mercle root`.
There are two bugs which caused these:
1. The pre-value is incorrect when adding journal for TransientStorage. It should be the previous one, but not the current one.
2. The op SelfDestruct6780 forgot to add its journal for revert. It should call SelfDestruct() to do it.
> bugfix: tstorage revert and selfdestruct6780 revert

- core/types/bundle_gasless.go
- miner/worker_builder.go
Add new field in SimulateGaslessBundleResp.
In high-traffic scenarios, simulategaslessbundle will reach the gaslimit and cause an error. A new field needs to be added to identify it.
N/A.
* Add new field in SimulateGaslessBundleResp.
> fix(op-geth): add new field in SimulateGaslessBundleResp

- core/blockchain.go
The issue arises when PBSS snapshots are created without stopping the system, leading to inconsistencies in safe and unsafe block heights due to data persistence order. This problem occurs specifically when engine-sync is enabled, preventing proper recovery.
This fix addresses an issue with starting snapshots created using PBSS in specific scenarios. PBSS snapshots generated without stopping can result in inconsistencies in the safe and unsafe block heights due to the order of data persistence. In cases where engine-sync is not enabled, the existing logic can automatically recover and start. However, when engine-sync is enabled, the initialization logic prevents entry into the op-node's recovery logic. Therefore, this fix adjusts the block height relationships during Geth initialization …
> fix: Fix pbss snapshot inconsistency with engine-sync enabled when starting

- core/parallel_state_scheduler.go
- core/state/pevm_statedb.go
- tests/block_test.go
The ut TestBlockchainWithTxDAGDebug failed and report two errors:
1.  invalid gas used:
```
--- FAIL: TestBlockchainWithTxDAG/InvalidBlocks/bcStateTests/transactionFromSelfDestructedContract.json/transactionFromSelfDestructedContract_London (0.00s)
block_test.go:134: test in path mode with snapshotter failed: block #1 insertion into chain failed: invalid gas used (remote: 95603 local: 70603)
--- FAIL: TestBlockchainWithTxDAG/InvalidBlocks/bcStateTests/transactionFromSelfDestructedContract.json/transactionFromSelfDestructedContract_Merge (0.00s)
block_test.go:134: test in path mode with snapshotter failed: block #1 insertion into chain failed: invalid gas used (remote: 95603 local: 70603)
--- FAIL: TestBlockchainWithTxDAG/InvalidBlocks/bcStateTests/transactionFromSelfDestructedContract.json …
```
> fix ut case of TestBlockchainWithTxDAGDebug

- core/blockchain.go
Use bc.CurrentBlock() instead of bc.CurrentHeader() when initializing txDAGReader.
When a block rollback occurs, using bc.CurrentBlock() is the way to get the correct starting block height.
none
> pevm: fix the blockNumber used by txDAGReader during initialization

- core/state/journal.go
- core/state/state_object.go
- core/state/statedb.go
> PEVM-fix: clear useless legacy pevm code

- .github/workflows/unit-test.yaml
- core/pevm_processor.go
- tests/fix_unit_test.patch
Some UTs are broken, and I tried to fix them.
* ...
> pevm: try to fix UT

- core/blockchain.go
There is no necessary to do prefetch for PEVM.
* ...
> PEVM-fix: Disable prefetch when PEVM enabled

- core/types/receipt.go
Fix gasless tx receipt l1 fee result.
When TipFeeCap is 0 and GasFeeCap is not, the effective gas price is 0, opBNB not charge L1 fee, but the result of tx receipt  
shows that l1fee is charged. 
https://testnet.opbnbscan.com/tx/0xf54b5aa2960baaed2d426c97f947ce79e39fd575047f55d2de9d8f8732833a63
* Fix gasless tx receipt l1 fee result, when effective gas price is 0, the l1 fee is 0.
> fix(op-geth): fix gasless receipt l1fee

- CHANGELOG.md
Add changelogs to v0.5.2.
NA
NA
NA
> doc: add changelogs to v0.5.2

- cmd/geth/main.go
- cmd/utils/flags.go
- core/blockchain.go
- core/pevm_processor.go
- core/vm/interpreter.go
- eth/backend.go
- eth/ethconfig/config.go
> feat: disable parallel when txs count is low

- CHANGELOG.md
- core/txpool/legacypool/legacypool.go
This is a minor release for opBNB Mainnet and Testnet.
It fixes a txpool memory leak bug that could cause out-of-memory issues.
It is recommended to upgrade to this version for both Mainnet and Testnet.
* fix: txpool reheap out-of-memory issues by @andyzhang2023 in https://github.com/bnb-chain/op-geth/pull/211
ghcr.io/bnb-chain/op-geth:v0.5.3
**Full Changelog**: https://github.com/bnb-chain/op-geth/compare/v0.5.2...v0.5.3
> prepare for v0.5.3 release 

- core/blockchain.go
fallback to serial processor when pevm execution result is not correct
* ...
> feat: PEVM fallback to serial process

- core/types/mvstates.go
The `cannotGasFeeDelay` flag was not set correctly, which can cause issues with the generated txDAG.
> pevm(txDAG): fix cannotGasFeeDelay setting bug

- core/state/snapshot/difflayer.go
tune bloom filter params of snapshot to fit higher tps
original bloom filter size is too small for opBNB 100m block gas limit, the error rate is 1 during load test.
we adjust it to fit opBNB throughput.
n/a
1. adjust the bloom size calculation to include all diffLayers and aggregatorLayer
2. scale up the size for bigger block gas limit of opBNB
3. scale down the error target rate 0.02 -> 0.01
> perf: tune snapshot bloom for higher tps

- beacon/engine/types.go
- consensus/beacon/consensus.go
- core/block_validator.go
- core/blockchain.go
- core/blockchain_test.go
- core/state/statedb.go
- core/types.go
- eth/catalyst/api.go
- eth/catalyst/queue.go
- miner/payload_building.go
This PR adds two changes to op-geth:
1. support new api engine_opSealPayload, this is the associated PR to https://github.com/bnb-chain/opbnb/pull/248
2. optimize several overheads in block mining to achieve higher TPS
Through load test, we found that it took about 200ms(10k tps case) to call/serve of engine apis and some overheads in block minting steps can be optimized. So we try to optimize it to achieve higher TPS.
n/a
* support new api engine_opSealPayload
```
1. op-node call engine_forkchoiceUpdated
2. wait scheduled time
3. op-node call sequentially: engine_getPayload -> engine_newPayload -> engine_forkchoiceUpdated
1. op-node call engine_forkchoiceUpdated
2. wait scheduled time
3. op-node call concurrently: engine_opSealPayloadResponse & engine_getPayload
```
* …
> perf: support new api engine_opSealPayload and optimize overheads of block mining

- core/state/pevm_statedb.go
> PEVM-fix: fix journal record in add/sub balance with 0

- cmd/geth/main.go
- cmd/utils/flags.go
- core/txpool/legacypool/async_priced_list.go
- core/txpool/legacypool/legacypool.go
- core/txpool/legacypool/legacypool_test.go
- core/txpool/legacypool/list.go
- miner/worker.go
An "async-reheap" priced list is introduced into txpool to get better performance. The re-heap of the whole transaction pool usually costs hundreds of ms, which blocks more transactions coming into the pool through the Add() function. So we develop a new type of priced list to resolve the bottleneck. 
The "async-reheap" finds the "lowest-priced" transactions async, and stores it into a cache, then it  does the "underpriced" validation quickly by the stored cache.
add flag ```--txpool.asyncpriced``` to enable this feature.
> Txpool opt async priced

- core/blockchain.go
> PEVM-fix: try load TxDAG from block if fail from file

- core/txpool/legacypool/legacypool.go
This PR is for fixing the issue of concurrent map reading and writing on the map of txpool.queue.
It was introduced by PR #247 , in which the numbers of pending and queued transactions were added to logs. 
The txpool.queue and txpool.pending should always be protected by the mu lock of txpool, So we use Stats() instead of stats();
Besides, there is no need to iterator the pending and queue lists to sum the total numbers. The variables pendingCounter and queueCounter records them.
> fix: txpool concurrent map issue

- cmd/geth/main.go
- cmd/utils/flags.go
- core/blockchain.go
- core/parallel_state_scheduler.go
- core/parallel_state_scheduler_test.go
- core/vm/interpreter.go
- eth/backend.go
- eth/ethconfig/config.go
A new option is added to improve the performance when the TxDAG contains a deep dependency chain. The performance might become poor when many transactions depend on each other in a block. So we add a threshold option under which the parallel EVM will be enabled, otherwise, the block will be processed by the original EVM in sequential.
Add flag ```--parallel.txdag-max-depth-ratio``` to enable this feature.  Default to be not enabled.
> pevm: fallback to sequencial processor when the TxDAG is too deep

- core/blockchain.go
add some metrics for parallel EVM processor
> add metrics for parallel processor

- cmd/utils/flags.go
- core/blockchain.go
Some improvements are added in the PR:
1. fix the default value of flag ```--parallel.txdag-max-depth-ratio```
2. change the metric of "parallel txs depth" from counter to gauge.
3. change the maindb of UncommittedDB from ParallelStateDB to StateDB, which caused a 20%+ decrease of performance.
> Fix pevm 20per performance issue

- beacon/engine/errors.go
- beacon/engine/types.go
- eth/catalyst/api.go
This pr fix error return of engine_opSealPaylaod api, related fix to op-node is https://github.com/bnb-chain/opbnb/pull/259
The error return of original engine_api is chaos and easy lead to bug, the new engine_opSealPayload api followed the original part, and unfortunately triggered bug, which will cause chain stuck if force kill
n/a
insert error stage to rpc error in OpSealPayload engine api
> fix: insert error stage to rpc error in OpSealPayload engine api

- releaseNote/Release Note - alpha.md
- releaseNote/Release Note - beta.md
This is the Beta Release of the Parallel Transaction Execution of op-geth
To speedup the execution stage of transactions by introducing the PEVM feature
* support loading TxDAG data from block on-chain
* support parallel state merge 
* support fallback mechanism to sequential run
* fix several issues
* verified the beta version of PEVM successfully sync to latest opBNB mainnet.
> PEVM: add beta release note

- .github/workflows/docker-release.yaml
Fix the `DockerImage build and push` ci action, which interrupts the automatic image generated & uploaded workflow.
https://github.com/bnb-chain/op-geth/actions/runs/13053301943/job/37322899096
```
#29 [linux/arm64 builder 8/8] RUN cd /go-ethereum && go run build/ci.go install -static ./cmd/geth
#29 167.3 # net
#29 167.3 gcc: internal compiler error: Segmentation fault signal terminated program cc1
#29 167.3 Please submit a full bug report, with preprocessed source (by using -freport-bug).
#29 167.3 See <https://gitlab.alpinelinux.org/alpine/aports/-/issues> for instructions.
#29 ERROR: process "/dev/.buildkit_qemu_emulator /bin/sh -c cd /go-ethereum && go run build/ci.go install -static ./cmd/geth" did not complete successfully: exit code: 1
------
> [linux/arm64 builder 8/8] RUN cd …
```
> fix: make docker image build and push job work
